# Generated by Django 5.0 on 2025-03-20 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="chatmessages",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="chat.conversation",
            ),
        ),
    ]
